//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShyamDhokiya_557_Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourites
    {
        public int FavoriteId { get; set; }
        public int UserId { get; set; }
        public int BikeId { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Users Users { get; set; }
    }
}
