//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShyamDhokiya_557_Model.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShyamDhokiya_557Entities : DbContext
    {
        public ShyamDhokiya_557Entities()
            : base("name=ShyamDhokiya_557Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<Bike> Bike { get; set; }
        public virtual DbSet<Favourites> Favourites { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
