//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizManagement_Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answer_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> quiz_id { get; set; }
        public Nullable<int> ques_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Options Options { get; set; }
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual Users Users { get; set; }
    }
}
