

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVCCrud_Model.Context
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class shyamEntities : DbContext
{
    public shyamEntities()
        : base("name=shyamEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<RegisterUser> RegisterUser { get; set; }

}

}

