
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVCCrud_Model.Context
{

using System;
    using System.Collections.Generic;
    
public partial class RegisterUser
{

    public int UserID { get; set; }

    public string FullName { get; set; }

    public string UserEmail { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

}

}
